[build]
  command = "npm run build" # Assuming you have a build script that compiles your client-side assets (if any)
  functions = "lambda"      # Directory where your serverless functions will be located
  publish = "public"        # Directory where your client-side build artifacts (if any) will be located

[[redirects]]
  from = "/api/*"          # Redirect all requests under /api/ to the serverless functions
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/api/*"           # Set CORS headers for the API routes
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "*"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

[dev]
  functions = "lambda"      # Directory for serverless functions in development mode
